-- ============================================================================
-- Games + Game Players tables
-- ----------------------------------------------------------------------------
-- Persists finalized live sessions so they appear on the History page and
-- survive across devices. Until this table existed, the live-game flow only
-- showed an in-memory "Game Finalized" screen and the history list was
-- backed by a hardcoded TypeScript array (`lib/historical-games.ts`) — so
-- nothing the host actually played ever made it to the dashboard.
--
-- The hardcoded array stays put as historical seed data; the games page
-- merges it with rows from this table at read time so the lifetime totals
-- don't reset to zero on day one.
--
-- Run in your Supabase SQL Editor. Idempotent — safe to re-run.
-- ============================================================================

CREATE TABLE IF NOT EXISTS games (
  -- Same id used in the live URL (`/games/<id>`), generated by the create
  -- form. Random base36 short hash today, but treated as opaque text here
  -- so the format can change without a migration.
  id              TEXT PRIMARY KEY,
  played_at       TIMESTAMPTZ NOT NULL,           -- session end (= finalize ts)
  date_label      TEXT NOT NULL,                  -- "May 31, 2026"
  duration_label  TEXT NOT NULL,                  -- "2h 30m"
  blinds_label    TEXT NOT NULL,                  -- "£0.25 / £0.50"
  small_blind     NUMERIC(10, 2),
  big_blind       NUMERIC(10, 2),
  location        TEXT NOT NULL,
  total_pot       NUMERIC(12, 2) NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by      UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_games_played_at ON games(played_at DESC);

CREATE TABLE IF NOT EXISTS game_players (
  game_id      TEXT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
  player_name  TEXT NOT NULL, -- original casing for display
  buy_in       NUMERIC(12, 2) NOT NULL DEFAULT 0,
  cash_out     NUMERIC(12, 2) NOT NULL DEFAULT 0,
  food         NUMERIC(12, 2) NOT NULL DEFAULT 0
);

-- One row per (game, player) case-insensitively — so "Toby" and "toby" can't
-- both land in the same game. Postgres won't accept an expression like
-- lower(player_name) in a table-level PRIMARY KEY, so the uniqueness is
-- enforced by this unique expression index instead. It doubles as the
-- lookup index for "all players in game X".
CREATE UNIQUE INDEX IF NOT EXISTS idx_game_players_game_player_lower
  ON game_players (game_id, lower(player_name));

-- Cross-game lookup by player name (e.g. a profile's session history).
CREATE INDEX IF NOT EXISTS idx_game_players_player_lower
  ON game_players (lower(player_name));

-- ----------------------------------------------------------------------------
-- Row Level Security
--   * SELECT: anyone (history pages render server-side with the anon key
--     before the auth cookie resolves, and non-admins still need to read).
--   * INSERT / UPDATE / DELETE: admins only — same pattern as
--     game_settlements. The live "End Game" button is host-driven; players
--     joining mid-session don't write.
-- ----------------------------------------------------------------------------
ALTER TABLE games ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_players ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "games_select_all"        ON games;
DROP POLICY IF EXISTS "games_insert_admin"      ON games;
DROP POLICY IF EXISTS "games_update_admin"      ON games;
DROP POLICY IF EXISTS "games_delete_admin"      ON games;

CREATE POLICY "games_select_all"
  ON games FOR SELECT
  USING (true);

CREATE POLICY "games_insert_admin"
  ON games FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.user_id = auth.uid() AND u.is_admin = true
    )
  );

CREATE POLICY "games_update_admin"
  ON games FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.user_id = auth.uid() AND u.is_admin = true
    )
  );

CREATE POLICY "games_delete_admin"
  ON games FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.user_id = auth.uid() AND u.is_admin = true
    )
  );

DROP POLICY IF EXISTS "game_players_select_all"   ON game_players;
DROP POLICY IF EXISTS "game_players_insert_admin" ON game_players;
DROP POLICY IF EXISTS "game_players_update_admin" ON game_players;
DROP POLICY IF EXISTS "game_players_delete_admin" ON game_players;

CREATE POLICY "game_players_select_all"
  ON game_players FOR SELECT
  USING (true);

CREATE POLICY "game_players_insert_admin"
  ON game_players FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.user_id = auth.uid() AND u.is_admin = true
    )
  );

CREATE POLICY "game_players_update_admin"
  ON game_players FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.user_id = auth.uid() AND u.is_admin = true
    )
  );

CREATE POLICY "game_players_delete_admin"
  ON game_players FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.user_id = auth.uid() AND u.is_admin = true
    )
  );
